### ISSUE TITLE
Maven Tests Failed Error while running Run-Microservies.sh script

### ISSUE THREAD

**Issue by aishwaryadhage** [airavata-courses/zeus#36] opened 2018-09-24 03:56 UTC
Hello Team Zeus,

I was trying to follow steps for installation mentioned on wiki page.
I am getting this maven-plugin error while running the Run-Microservies.sh script. 
Below is the error-

Test set: com.abharatha.JavaSpringBoot.LearningSpringBootApplicationTests
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 8.303 s <<< FAILURE! - in com.abharatha.JavaSpringBoot.LearningSpringBootApplicationTests
testRepository(com.abharatha.JavaSpringBoot.LearningSpringBootApplicationTests)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

givenSearchStr_whenGetSearchVideos_thenExpectStatusOK(com.abharatha.JavaSpringBoot.LearningSpringBootApplicationTests)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

Please let me know if I am missing any steps while trying to run the script.

Thanks.

**Comment by BharathaAravind** [comment] 2018-09-24 04:03
Hi Aishwarya,

I think the db schema is not loaded properly. Can you create a new mysql user with both username and password and update in the constants.js as mentioned in the wiki.

**Comment by aishwaryadhage** [comment] 2018-09-24 21:36
Thanks Aravind,

 I have updated mysql user with both username and password. 

The above issue was with java version. I updated pom.xml and had to add java 9 dependency.
I think you should also mention the java version in the installation guide wiki page.

**Comment by aishwaryadhage** [comment] 2018-09-24 21:50
Thanks Aravind,
I updated the new mysql user with both username and password.

Also I think the above error was because of my java version. And fixed I fixed it for my java version.
I think you can also add that for which version

**Comment by BharathaAravind** [comment] 2018-09-25 00:12
I mentioned the Java Version in the WIKI page as you mentioned.
Thanks for running after adding the dependency. Since the issue is resolved I am closing the issue.

**Closed by BharathaAravind** 2018-09-25 00:12 UTC
