### ISSUE TITLE
Error in bringing node controller up

### ISSUE THREAD

**Issue by harshallpandit** [airavata-courses/zeus#38] opened 2018-09-25 23:19 UTC
I followed the instructions.
- cloned the repo
- changed database username and password
- ran npm install
when I do node app.js I get this error -

```
 -- Dump completed on 2018-09-13 21:25:0
importSQL done: data.sql
DONE!
all statements have been executed

D:\Work\Science Gateway\peer review\NodeControllerWork\zeus\noderest_controller\node_modules\mysql\lib\protocol\Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^
ERROR: Error: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'

```
I see that it has created a database in mysql named zeus_flask but zeus_node and zeus_spring databases are not getting created. There is no error regarding data dump on the console.

**Comment by BharathaAravind** [comment] 2018-09-25 23:42
Hi @harshallpandit,

The collation error usually occurs when an older version of mysql is being used. Can you please let us know which version of mysql is installed in your pc.

Thanks,
Aravind.

**Comment by harshallpandit** [comment] 2018-09-26 02:04
It worked after I upgraded Mysql to version 8 and followed steps for installation and build.
Everything works fine. Documentation is good and installation steps are simple.

**Comment by BharathaAravind** [comment] 2018-09-26 02:11
Thanks Harshall. Closing the issue since as the problem is resolved.

**Closed by BharathaAravind** 2018-09-26 02:11 UTC
Labels: bug
